import { useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

type Message = { id: string; role: "user" | "assistant"; text: string; name?: string };
const starter: Message[] = [{ id: "welcome", role: "assistant", name: "Lía", text: "Soy tu mesa editorial. Puedo diagnosticar un fragmento, sugerir cambios, reescribir por tono o ayudarte a convertir una intuición en una hipótesis comercial." }];

export default function ChatScreen() {
  const colors = useColors(); const [value, setValue] = useState(""); const [messages, setMessages] = useState<Message[]>(starter);
  const chat = trpc.editorial.chat.useMutation({ onSuccess: (data) => setMessages((current) => [...current, { id: `${Date.now()}-assistant`, role: "assistant", name: data.specialist, text: data.text }]) });
  const send = () => { const text = value.trim(); if (!text || chat.isPending) return; setMessages((current) => [...current, { id: `${Date.now()}-user`, role: "user", text }]); setValue(""); chat.mutate({ message: text }); };
  return <ScreenContainer className="px-5 pt-4"><KeyboardAvoidingView className="flex-1" behavior={Platform.OS === "ios" ? "padding" : undefined} keyboardVerticalOffset={90}><View className="flex-row items-center justify-between mb-5"><View><Text className="text-sm text-muted font-semibold tracking-widest">EQUIPO EDITORIAL</Text><Text className="text-3xl font-bold text-foreground mt-1">Hablemos del libro</Text></View><View style={{ backgroundColor: colors.primary }} className="w-10 h-10 rounded-full items-center justify-center"><IconSymbol name="bubble.left.and.bubble.right.fill" color={colors.background} size={20} /></View></View><ScrollView className="flex-1" contentContainerStyle={{ paddingBottom: 18 }} showsVerticalScrollIndicator={false}>{messages.map((message) => <View key={message.id} className={`mb-3 max-w-[88%] ${message.role === "user" ? "self-end" : "self-start"}`}><Text className="text-[11px] text-muted font-semibold mb-1 ml-1">{message.role === "user" ? "TÚ" : message.name?.toUpperCase()}</Text><View style={message.role === "user" ? { backgroundColor: colors.foreground } : undefined} className={`rounded-2xl px-4 py-3 ${message.role === "user" ? "rounded-tr-sm" : "bg-surface border border-border rounded-tl-sm"}`}><Text style={message.role === "user" ? { color: colors.background } : undefined} className={`text-[15px] leading-6 ${message.role === "user" ? "" : "text-foreground"}`}>{message.text}</Text></View></View>)}{chat.isPending && <View className="self-start bg-surface border border-border rounded-2xl px-4 py-3 flex-row items-center"><ActivityIndicator size="small" color={colors.primary} /><Text className="text-muted text-sm ml-2">El equipo está pensando…</Text></View>}</ScrollView><View className="bg-surface border border-border rounded-2xl p-2 flex-row items-end mb-2"><TextInput value={value} onChangeText={setValue} placeholder="Pega un fragmento o plantea una decisión…" placeholderTextColor={colors.muted} multiline maxLength={12000} returnKeyType="send" onSubmitEditing={send} className="flex-1 text-foreground px-3 py-2 min-h-[44px] max-h-[120px]" /><Pressable onPress={send} style={({ pressed }) => [{ backgroundColor: colors.foreground, opacity: pressed ? 0.65 : 1 }]} className="w-11 h-11 rounded-xl items-center justify-center"><IconSymbol name="paperplane.fill" color={colors.background} size={18} /></Pressable></View></KeyboardAvoidingView></ScreenContainer>;
}
