import { useMemo, useState } from "react";
import { Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { economicScenarios } from "@/shared/editorial";

const tools = [
  { id: "diagnostico", icon: "doc.text.fill" as const, title: "Diagnóstico editorial", description: "Detecta ritmo, claridad, foco y problemas de coherencia.", prompt: "Analiza este fragmento en 4 capas: claridad, ritmo, coherencia y oportunidad de mejora." },
  { id: "reescritura", icon: "wand.and.stars" as const, title: "Reescritura por intención", description: "Conserva la voz y prueba variantes de tono, tensión o concisión.", prompt: "Reescribe este fragmento manteniendo la voz, pero aumentando la tensión narrativa." },
  { id: "estrategia", icon: "chart.bar.fill" as const, title: "Estrategia y lanzamiento", description: "Convierte intuiciones en hipótesis de audiencia y posicionamiento.", prompt: "Construye 3 hipótesis comerciales para este libro, con audiencia, promesa y riesgo." },
  { id: "estilo", icon: "folder.fill" as const, title: "Dirección de estilo", description: "Define referencias, paleta, composición y reglas visuales sin generar imágenes.", prompt: "Propón una dirección visual coherente con VISUAL_BIBLE_v1.md y separa reglas de referencias." },
];

function parseAmount(value: string) { const normalized = value.replace(",", "."); const parsed = Number(normalized); return Number.isFinite(parsed) && parsed >= 0 ? parsed : 0; }

type EconomicInput = { label: string; value: string; setter: (value: string) => void };

export default function ToolsScreen() {
  const colors = useColors();
  const [selected, setSelected] = useState(tools[0]);
  const [price, setPrice] = useState(""); const [cost, setCost] = useState("");
  const [low, setLow] = useState(""); const [mid, setMid] = useState(""); const [high, setHigh] = useState("");
  const economics = useMemo(() => { const unitPrice = parseAmount(price); const unitCost = parseAmount(cost); return economicScenarios.map((scenario, index) => { const sales = [parseAmount(low), parseAmount(mid), parseAmount(high)][index]; return { ...scenario, revenue: sales * unitPrice, profit: sales * (unitPrice - unitCost) }; }); }, [price, cost, low, mid, high]);
  const economicInputs: EconomicInput[] = [{ label: "Bajo", value: low, setter: setLow }, { label: "Medio", value: mid, setter: setMid }, { label: "Alto", value: high, setter: setHigh }];
  return <ScreenContainer className="px-5 pt-4"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 28 }}><Text className="text-sm text-muted font-semibold tracking-widest">MESA DE TRABAJO</Text><Text className="text-3xl font-bold text-foreground mt-1 mb-2">Herramientas claras</Text><Text className="text-muted text-[15px] leading-6 mb-6">Elige una intención. El equipo te devolverá una salida concreta, no ruido.</Text>{tools.map((tool) => { const active = selected.id === tool.id; return <Pressable key={tool.id} onPress={() => setSelected(tool)} style={({ pressed }) => [{ opacity: pressed ? 0.72 : 1 }, active ? { backgroundColor: colors.foreground, borderColor: colors.foreground } : {}]} className={`rounded-2xl border p-4 mb-3 ${active ? "" : "border-border bg-surface"}`}><View className="flex-row items-start"><View className="w-10 h-10 rounded-xl bg-background items-center justify-center"><IconSymbol name={tool.icon} color={active ? colors.background : colors.primary} size={20} /></View><View className="flex-1 ml-3"><Text style={active ? { color: colors.background } : undefined} className={`text-base font-bold ${active ? "" : "text-foreground"}`}>{tool.title}</Text><Text style={active ? { color: colors.background, opacity: 0.7 } : undefined} className={`text-sm leading-5 mt-1 ${active ? "" : "text-muted"}`}>{tool.description}</Text></View></View></Pressable>; })}
    <View className="rounded-2xl bg-surface border border-border p-5 mt-3"><Text className="text-xs text-muted font-semibold tracking-widest">PLANTILLA LISTA</Text><Text className="text-foreground font-bold text-lg mt-2">{selected.title}</Text><Text className="text-muted text-sm leading-5 mt-2">{selected.prompt}</Text><Pressable style={({ pressed }) => [{ backgroundColor: colors.foreground, opacity: pressed ? 0.7 : 1 }]} className="rounded-xl px-4 py-3 mt-4"><Text style={{ color: colors.background }} className="font-semibold text-center">Abrir en el equipo</Text></Pressable></View>
    <View className="rounded-2xl bg-surface border border-border p-5 mt-5"><View className="flex-row items-center"><IconSymbol name="chart.bar.fill" color={colors.primary} size={20} /><Text className="text-foreground text-lg font-bold ml-2">Economía del lanzamiento</Text></View><Text className="text-muted text-sm leading-5 mt-2">Mara calcula tres escenarios con tus supuestos. No hay cifras precargadas.</Text><View className="flex-row gap-2 mt-4"><TextInput value={price} onChangeText={setPrice} keyboardType="decimal-pad" placeholder="Precio unitario" placeholderTextColor={colors.muted} className="flex-1 bg-background border border-border rounded-xl px-3 py-3 text-foreground" /><TextInput value={cost} onChangeText={setCost} keyboardType="decimal-pad" placeholder="Coste unitario" placeholderTextColor={colors.muted} className="flex-1 bg-background border border-border rounded-xl px-3 py-3 text-foreground" /></View><Text className="text-xs text-muted mt-4 mb-2">Unidades estimadas por escenario</Text><View className="flex-row gap-2">{economicInputs.map((input) => <View key={input.label} className="flex-1"><Text className="text-[11px] text-muted mb-1">{input.label}</Text><TextInput value={input.value} onChangeText={input.setter} keyboardType="number-pad" placeholder="—" placeholderTextColor={colors.muted} className="bg-background border border-border rounded-xl px-3 py-3 text-foreground" /></View>)}</View><View className="mt-4">{economics.map((scenario) => <View key={scenario.id} className="flex-row items-center justify-between border-t border-border py-3"><View><Text className="text-foreground font-semibold">{scenario.label}</Text><Text className="text-muted text-xs">{scenario.description}</Text></View><View className="items-end"><Text className="text-foreground font-bold">{scenario.revenue ? scenario.revenue.toFixed(2) : "—"}</Text><Text className="text-muted text-xs">beneficio: {scenario.profit ? scenario.profit.toFixed(2) : "—"}</Text></View></View>)}</View></View>
  </ScrollView></ScreenContainer>;
}
